name: Deploy

on:
  push:
    tags:
      - v**
      - '!**beta**'

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Docker Image Url
        id: image
        env:
          URL: mmx233/bitsrunlogin-go
        run: |
          echo LATEST=${URL}:latest >> $GITHUB_OUTPUT
          echo VERSION=${URL}:${GITHUB_REF/refs\/tags\//} >> $GITHUB_OUTPUT

      - name: Setup QEMU Emulator
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Setup Docker Buildx Command
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to docker registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.rgs_u }}
          password: ${{ secrets.rgs_p }}

      - name: Build Docker Image and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7
          tags: ${{ steps.image.outputs.VERSION }},${{ steps.image.outputs.LATEST }}